# Noydra buraya java dosya yolu belirtme l?tfen local.properties i?erisinde belirt.
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

tor.bundle.version=15.0.19
tor.sha256.windows.x86_64=6ac067402c7b4a3dc37887ed3754b3914b67fdc220c966190683e9ccf91abf0f
tor.sha256.linux.x86_64=5a8f19f5f119b5fa2a8fd799a3a532e3236ad36164241800d6302e32f0e1c2a9
tor.sha256.macos.x86_64=95243f76bcf05d6179d017c3f3e4ece7b53cc58dff1ba617b03a2fe2c8298b5b
tor.sha256.macos.aarch64=c99cf6f69740a443c7fffaf598ceb0952b3914041507c8afe11bed84a3333eb1
tor.sha256.android.aarch64=bdbc39ca4d9e77912ef0fc633cdc57d0eb8ed9521e6d62497ea33f0feeec53b2
tor.sha256.android.armv7=e7d976c1c892e988ae05d62bef3fecbbda0a74afd09339f40fa8c0024032054e
tor.sha256.android.x86_64=378d98e3f1ae78cec80a1e9631e6a97d9e400cc8db2a8a647b1eddb751bd7521
tor.sha256.android.x86=40372814ca3600bbbd9111d4b8d26f67689f8206f8e7ad67eae292bad0365399

org.gradle.tooling.parallel=true
